export const REFRESH_LANDING_ON = "REFRESH_LANDING_ON"
export const REFRESH_LANDING_OFF = "REFRESH_LANDING_OFF"

export const GET_CONTACTS = "GET_CONTACTS"
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED"

export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS"
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS"
export const GET_CONTACT_DETAILS_FAILED = "GET_CONTACT_DETAILS_FAILED"

export const FIRST_NAME = "FIRST_NAME"
export const LAST_NAME = "LAST_NAME"
export const AGE = "AGE"
export const PHOTO_LINK = "PHOTO_LINK"

export const RESET_CONTACT_DATA = "RESET_CONTACT_DATA"




